from aiogram.types import ReplyKeyboardMarkup, KeyboardButton             
                       

econom = KeyboardButton("Экономические профессии")
med = KeyboardButton("Медицинские профессии")
it = KeyboardButton("IT профессии ")
ingen = KeyboardButton("Технические\Инженерные/строительные профессии/ручной труд")
since = KeyboardButton("Научные профессии")
tvor = KeyboardButton("Творческие профессии")
urustick = KeyboardButton("Юридические, правоохранительны")
nabor_sferi = ReplyKeyboardMarkup(resize_keyboard=True, row_width=1)
nabor_sferi.add(econom,med,it,ingen,since,tvor,urustick)


nabor_sity=ReplyKeyboardMarkup(resize_keyboard=True, row_width=1)
mosck = KeyboardButton("Москва и Мос область")
spb = KeyboardButton("Санкт-Петербург")
sib = KeyboardButton("Новосибирск")
eca = KeyboardButton("Екатеринбург")
kaz = KeyboardButton("Казань")
nov = KeyboardButton("Нижний Новгород")
cheba = KeyboardButton("Челябинск")
sam = KeyboardButton("Самара")
perm = KeyboardButton("Пермь")
nabor_sity.add(mosck,spb,sib,kaz,eca,nov,cheba,sam,perm)

#Экономические професии 
nabor_eco=ReplyKeyboardMarkup(resize_keyboard=True, row_width=1)
mosck = KeyboardButton("Аудитор")
prof_one = KeyboardButton("Аналитик")
prof_two = KeyboardButton("Брокер")
prof_tree = KeyboardButton("Екатеринбург")
prof_fr = KeyboardButton("Продавец")
prof_fi = KeyboardButton("Кредитный консультант")
prof_six = KeyboardButton("Маркетолог")
prof_sev = KeyboardButton("Страховой агент")
prof_ete = KeyboardButton("Торговый представитель")
prof_nine = KeyboardButton("Экономист")
prof_ten = KeyboardButton("Финансист")
nabor_eco.add(prof_one,prof_two,prof_tree,prof_fr,prof_fi,prof_six,prof_sev,prof_ete,prof_nine,prof_ten )

#IT проффесии
nabor_it=ReplyKeyboardMarkup(resize_keyboard=True, row_width=1)
mosck = KeyboardButton("Администратор базы данных")
prof_one = KeyboardButton("Веб-интеграторT")
prof_two = KeyboardButton("Оператор ПК")
prof_tree = KeyboardButton("Веб-мастер")
prof_fr = KeyboardButton("Программист")
prof_fi = KeyboardButton("Кодер")
prof_six = KeyboardButton("Веб-программист")
prof_sev = KeyboardButton("Тестировщик")
prof_ete = KeyboardButton("Геймдизайнер")
prof_nine = KeyboardButton("Программист")
prof_ten = KeyboardButton("Системный администратор")
nabor_it.add(prof_one,prof_two,prof_tree,prof_fr,prof_fi,prof_six,prof_sev,prof_ete,prof_nine,prof_ten )

#Медецински профессии 
nabor_med=ReplyKeyboardMarkup(resize_keyboard=True, row_width=1)
mosck = KeyboardButton("Акушер-гинеколог")
prof_one = KeyboardButton("Аллерголог")
prof_two = KeyboardButton("Венеролог")
prof_tree = KeyboardButton("Врач скорой медицинской помощи")
prof_fr = KeyboardButton("Гастроэнтеролог ")
prof_fi = KeyboardButton("Дерматолог")
prof_six = KeyboardButton("Диетолог")
prof_sev = KeyboardButton("Кардиолог")
prof_ete = KeyboardButton("Косметолог")
prof_nine = KeyboardButton("Нарколог")
prof_ten = KeyboardButton("Онколог")
prof_eleven = KeyboardButton("Ортодонт")
prof_twelw = KeyboardButton("Ортопед")
prof_trinadtcat = KeyboardButton("Офтальмолог")
prof_fotin = KeyboardButton("Пластический хирург")
prof_fiften = KeyboardButton("Проктолог")
prof_sixten = KeyboardButton("Психиатр")
prof_eleventen = KeyboardButton("Психотерапевт")
prof_twelwten = KeyboardButton("Рентгенолог")
prof_ninten = KeyboardButton("Терапевт")
prof_twentyone = KeyboardButton("Травматолог")
prof_twentytwo = KeyboardButton("Фармацевт")
prof_twentytree = KeyboardButton("Фельдшер")
prof_twentyfore = KeyboardButton("Хирург")
prof_twentyfive = KeyboardButton("Уролог")
prof_twentysix = KeyboardButton("Эндокринолог")
prof_twentysewen = KeyboardButton("Эпидемиолог")
nabor_med.add(prof_one,prof_two,prof_tree,prof_fr,prof_fi,prof_six,prof_sev,prof_ete,prof_nine,prof_ten,prof_eleven,prof_twelw ,prof_trinadtcat ,prof_fotin ,prof_fiften ,prof_sixten ,prof_eleventen ,prof_twelwten ,prof_ninten ,prof_twentytwo ,prof_twentyone ,prof_twentytree ,prof_twentyfore ,prof_twentyfive ,prof_twentysix,prof_twentysewen )

#Научные професии
nabor_sni=ReplyKeyboardMarkup(resize_keyboard=True, row_width=1)
mosck = KeyboardButton("Философ")
prof_one = KeyboardButton("Физик")
prof_two = KeyboardButton("Биолог")
prof_tree = KeyboardButton("Футуролог")
prof_fr = KeyboardButton("Географ")
prof_fi = KeyboardButton("Геодезист")
prof_six = KeyboardButton("Зоолог")
prof_sev = KeyboardButton("Логик")
prof_ete = KeyboardButton("Эколог")
prof_nine = KeyboardButton("Математик")
prof_ten = KeyboardButton("Социолог")
nabor_sni.add(prof_one,prof_two,prof_tree,prof_fr,prof_fi,prof_six,prof_sev,prof_ete,prof_nine,prof_ten )

#Инженерные професии 
nabor_inge=ReplyKeyboardMarkup(resize_keyboard=True, row_width=1)
mosck = KeyboardButton("Автослесарь")
prof_one = KeyboardButton("Автоэлектрик")
prof_two = KeyboardButton("Инженер-конструктор")
prof_tree = KeyboardButton("Инженер-механик")
prof_fr = KeyboardButton("Инженер по Технике Безопасности")
prof_fi = KeyboardButton("Инженер-системотехник")
prof_six = KeyboardButton("Инженер-строитель")
prof_sev = KeyboardButton("Кабельщик")
prof_ete = KeyboardButton("Кровельщик")
prof_nine = KeyboardButton("Маляр")
prof_ten = KeyboardButton("Механик")
prof_eleven = KeyboardButton("Монтажник")
prof_twelw = KeyboardButton("Плотник")
prof_trinadtcat = KeyboardButton("Сантехник")
prof_fotin = KeyboardButton("Сборщик")
prof_fiften = KeyboardButton("Сварщик")
prof_sixten = KeyboardButton("Техник")
prof_eleventen = KeyboardButton("Токарь")
prof_twelwten = KeyboardButton("Швея")
prof_ninten = KeyboardButton("Штукатур")
prof_twentyone = KeyboardButton("Электрик")
nabor_inge.add(prof_one,prof_two,prof_tree,prof_fr,prof_fi,prof_six,prof_sev,prof_ete,prof_nine,prof_ten,prof_eleven,prof_twelw ,prof_trinadtcat ,prof_fotin ,prof_fiften ,prof_sixten ,prof_eleventen ,prof_twelwten ,prof_ninten )

nabor_tvor=ReplyKeyboardMarkup(resize_keyboard=True, row_width=1)
mosck = KeyboardButton("Актёр")
prof_one = KeyboardButton("Балерина")
prof_two = KeyboardButton("Визажист")
prof_tree = KeyboardButton("Иллюстратор")
prof_fr = KeyboardButton("Модель")
prof_fi = KeyboardButton("Фотомодель")
prof_six = KeyboardButton("Фотограф")
prof_sev = KeyboardButton("Танцор")
prof_ete = KeyboardButton("Вокалист")
prof_nine = KeyboardButton("Гитарист")
prof_ten = KeyboardButton("Композитор")
prof_eleven = KeyboardButton("Режиссёр")
prof_twelw = KeyboardButton("Танцор")
prof_trinadtcat = KeyboardButton("Флорист")
prof_fotin = KeyboardButton("Художник")             
nabor_tvor.add(prof_one,prof_two,prof_tree,prof_fr,prof_fi,prof_six,prof_sev,prof_ete,prof_nine,prof_ten,prof_eleven,prof_twelw ,prof_trinadtcat ,prof_fotin )       


nabor_ur=ReplyKeyboardMarkup(resize_keyboard=True, row_width=1)
mosck = KeyboardButton("Адвокат")
prof_one = KeyboardButton("Кинолог")
prof_two = KeyboardButton("Государственный исполнитель")
prof_tree = KeyboardButton("Нотариус")
prof_fr = KeyboardButton("Правовед")
prof_fi = KeyboardButton("Прокурор")
prof_six = KeyboardButton("Работник органов ЗАГСа")
prof_sev = KeyboardButton("Телохранитель")
prof_ete = KeyboardButton("Юрисконсульт")
prof_nine = KeyboardButton("Юрист")
prof_ten = KeyboardButton("Таможенник")
nabor_ur.add(prof_one,prof_two,prof_tree,prof_fr,prof_fi,prof_six,prof_sev,prof_ete,prof_nine,prof_ten )


spis_kay={
    "Экономические профессии":nabor_eco,
    "Медицинские профессии":nabor_med,
    'IT профессии':nabor_it,
    "Технические\Инженерные/строительные профессии/ручной труд":nabor_inge,
    "Научные профессии":nabor_sni,
    "Творческие профессии":nabor_tvor,
    "Юридические, правоохранительны":nabor_ur

}